# Generated by Django 3.1.4 on 2020-12-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
    ]
