# Generated by Django 3.1.4 on 2020-12-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_sobrenome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
