# Generated by Django 3.1.4 on 2020-12-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco_produto', models.FloatField()),
                ('marca_produto', models.CharField(max_length=100)),
                ('reviewScore', models.SmallIntegerField()),
                ('favorito', models.BooleanField(default=True)),
            ],
        ),
    ]
